### ISSUE TITLE
How to rectify the CATS dataset?

### ISSUE THREAD

**Issue by xuqingyu26** [honeygupta/PAGSR#3]
Amazing works! It will be better if the code of dealing with the CATS dataset is released.

**Comment by honeygupta** [comment]
Hi, and thanks for showing interest in our work. Can you please explain what do you mean by the code dealing with the dataset?

**Comment by xuqingyu26** [comment]
In paper, CATS dataset is processed similar to FLIR-ADAS dataset. I'm interested in the way of identifying the correspondences and estimating the relative transformation matrices between image pairs.

**Comment by honeygupta** [comment]
We manually identified the correspondences. The process is similar to the one mentioned in this example - [link](https://www.mathworks.com/help/vision/ug/uncalibrated-stereo-image-rectification.html), but instead of using SURF or any other features for determining the correspondences, we manually chose the 2D points in the image.
